os:
  - linux
services:
  - docker
language: node_js
node_js:
  - 12.16.1
cache:
  directories:
    - node
    - node_modules
    - '$HOME/.m2'
env:
  global:
    - NODE_VERSION=12.16.1
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false
    - JHI_DISABLE_WEBPACK_LOGS=true
    - NG_CLI_ANALYTICS="false"
    - MAVEN_USER_HOME=$HOME/.m2/repository/
    - secure: P2eNzBdk/1vkEacos9q7W4Nr7Qjohe1UZp2D+EHDKSGJC8NxjOCLIlG1U83YGfC8OKrnjVzA0lGr2jSa/rBoPjHoM59M9TGZcFkBWdIAUN4chfudymFzDr08W1z/UsBxwTDYdLN0kifAiX4dVxL4OLeGJh8fbEea2E0wElu5x6zWn2nUQydowIz2HH44ieMSEtPR9jIjN8B3UrtDC0QkRYJ8fxT8kmTNcao14urKdMNILXLg5GVymeYeSbBD06d8IM1GPvWzkFti9wBJO5Um7a/SDXHZwaOzDCEvuosv3lnUMa/PatI5Wj6j6ZZWu+uxwARAX6S/eh0lqCBpUTct+H7I39MN+MkUOeW2Re/36hCX+eGgUPEfx2KfsEmSnIs23nD8S82VMjvftEOsdLRKitDnR7fBZE+XMCbAGnIEDDTwuBll/s3h8WWXcmZPFxA+3R0UXzO+SeTecTBqpqoM1j88TLZmvVVcNFlCPIq8BnIFJ4oin3ijiJUHaA2LhM+OPxFK+/2y+/i+8a2WlAVf1nAO5JkM+7ezCoKpjywA2E1enFShtXrbeV8x7VL1UV4UzKHJUi+4hGuzieRZFZcO2vNwzEbBciGDUNQ0myb1v33OU3TUOf7Q4NmyuEU/qB8Tts+crMcRW2iERzFzAXMkULlk3mmG5Pvw+WH/oqSXf+4=
before_install:
  - |
    if [[ $JHI_JDK = '8' ]]; then
      echo '*** Using OpenJDK 8'
    else
      echo '*** Using OpenJDK 11 by default'
      sudo add-apt-repository ppa:openjdk-r/ppa -y
      sudo apt-get update -q
      sudo apt-get install -y openjdk-11-jdk -y
      sudo update-java-alternatives -s java-1.11.0-openjdk-amd64
      java -version
    fi
  - java -version
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  - nvm install $NODE_VERSION
  - npm install -g npm
  - node -v
  - npm -v
install:
  - npm install
script:
  - chmod +x mvnw
  - './mvnw -ntp checkstyle:check'
  - './mvnw -ntp clean verify'
  - "./mvnw -ntp com.github.eirslett:frontend-maven-plugin:npm -Dfrontend.npm.arguments='run
    test' -Dmaven.repo.local=$MAVEN_USER_HOME"
  - './mvnw -ntp verify -Pprod -DskipTests'
notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false
